### PR TITLE
Committed fix to function inside closure - this.wrapIn....

### PR DESCRIPTION
**Pull request by wrschneider**
This is to fix an issue after upgrading to Grails 2.3.1

See http://jira.grails.org/browse/GRAILS-10651

### CODE REVIEW

**Comment by pdemilly** [comment]
Looking forward to have this pull request merged. Without it we cannot use scoped-proxy in any version above 2.3.0

**Comment by ldaley** [comment]
Would someone mind updating the plugin to build with a recent version of Grails? 

I'll push a new version when I receive this.

**Comment by keithrz** [comment]
I tried updating the plugin to build with a recent version of Grails.  But I'm still having some issues.  Please see link:
http://grails.1312388.n4.nabble.com/autowire-issue-scoped-proxy-even-after-fix-for-GRAILS-10651-td4653251.html

**Comment by keithrz** [comment]
Even with the error I am getting, I think it is still worth it to create a 0.3 version with the fix in this pull request.

I created a new pull request for upgrading to Grails 2.3.4.
https://github.com/alkemist/grails-scoped-proxy/pull/2

**Pull request merged**
